title: Githubyoooo
author: CaptainJack
email: zhangxianlei117@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  尝试学习

# social links
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
